#!/usr/bin/env python3
"""Create local demo sites and generate an mkcert certificate.

Usage:
  python3 setup_sites.py [--hosts] [--json PATH] [--cert-name NAME]

By default it reads `intersecting_48_topics_sites.json` in the same folder,
creates `sites/<domain>/index.html` for each domain, and generates
`cert-cert.pem`/`cert-key.pem` using `mkcert` (if available).
"""

import argparse
import re
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_JSON = ROOT / "intersecting_48_topics_sites.json"
SITES_DIR = ROOT / "sites"


def load_mapping(json_path: Path):
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


def invert_mapping(mapping):
    d = {}
    for topic, domains in mapping.items():
        for domain in domains:
            d.setdefault(domain, []).append(topic)
    return d


def create_site_files(domain_topics_map: dict, adhost: str, port: int):
    SITES_DIR.mkdir(exist_ok=True)
    for domain, topics in domain_topics_map.items():
        site_dir = SITES_DIR / domain
        site_dir.mkdir(parents=True, exist_ok=True)
        index_path = site_dir / "index.html"
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(make_index(domain, topics, adhost, port))
        # We create a single shared `/adtech.html` and `/witness.js` at the
        # repo root during setup so all sites can embed `/adtech.html`.
        # (The migration script or the server fallback will ensure the shared
        # files are served when a site requests `/adtech.html`.)


def make_index(domain, topics, adhost, port):
    topics_list = "\n".join(f"<li>{t}</li>" for t in sorted(topics))
    # The publisher page includes a hidden advertiser iframe pointing at the global adhost.
    # It also listens for postMessage 'getTopics' calls and responds with the Topics API result.
    return """<!doctype html>
<html>
<head>
    <meta charset="utf-8"> 
    <title>{domain}</title>
    <meta http-equiv="Permissions-Policy" content="browsing-topics=*">
    <style>body{{font-family: system-ui, sans-serif; margin:20px}} iframe#adtech{{display:block;width:100%;height:360px;border:1px solid #ddd;border-radius:8px}}</style>
</head>
<body>
    <h1>Demo site: {domain}</h1>
    <p>Topics associated with this origin:</p>
    <ul>
        {topics_list}
    </ul>
    <p>This site was generated by <code>final-demo/setup_sites.py</code>.</p>

    <!-- Visible local advertiser iframe (shared root adtech) -->
    <iframe id="adtech" src="/adtech.html" allow="browsing-topics"></iframe>

    <script>
    // Respond to cross-origin requests for topics. Message format: {{type:'getTopics', skipObservation: boolean}}
    window.addEventListener('message', async (e) => {{
        try {{
            const data = e.data || {{}};
            if (data.type === 'getTopics') {{
                let topics = [];
                if (typeof document.browsingTopics === 'function') {{
                    try {{
                        topics = await document.browsingTopics({{ skipObservation: !!data.skipObservation }});
                    }} catch (err) {{
                        // swallow
                    }}
                }}
                // Reply to source with topics and origin info
                try {{ e.source.postMessage({{ type: 'topicsResponse', payload: {{ origin: location.hostname, topics }} }}, '*'); }} catch (err) {{}}
            }}
        }} catch (err) {{}}
    }});
    </script>
</body>
</html>
""".format(
        domain=domain, topics_list=topics_list, adhost=adhost, port=port
    )


def make_ad_frame(adhost, publisher_domains, port):
    domains_json = json.dumps(publisher_domains)
    return """<!doctype html>
<html>
<head>
    <meta charset="utf-8"> 
    <title>Global Ad Tech</title>
    <meta http-equiv="Permissions-Policy" content="browsing-topics=*">
    <style>
        body{{font-family: system-ui, sans-serif; padding:12px;}}
        button{{padding:8px 10px; border-radius:8px;}}
        pre{{background:#fafafa;border:1px solid #eee;padding:10px;border-radius:6px;max-height:300px;overflow:auto}}
    </style>
</head>
<body>
    <h2>Global Advertiser UI ({adhost})</h2>
    <div>
        <button id="collect">Retrieve Topics From All Sites</button>
        <label><input id="observe" type="checkbox" checked> observe</label>
    </div>
    <pre id="out">—</pre>

    <script>
    const ALL_DOMAINS = {domains_json};
    const PORT = {port};
    const out = document.getElementById('out');
    const btnCollect = document.getElementById('collect');
    const observe = document.getElementById('observe');

    btnCollect.addEventListener('click', () => {{
        out.textContent = 'Collecting from ' + ALL_DOMAINS.length + ' sites...';
        const results = [];
        let pending = ALL_DOMAINS.length;
        function finish() {{ out.textContent = JSON.stringify(results, null, 2); }}

        ALL_DOMAINS.forEach(domain => {{
            try {{
                const frame = document.createElement('iframe');
                frame.style.display = 'none';
                frame.allow = 'browsing-topics';
                frame.src = `https://${{domain}}:${{PORT}}/`;
                document.body.appendChild(frame);

                const onMessage = (ev) => {{
                    if (!ev?.data) return;
                    if (ev.data.type === 'topicsResponse' && ev.data.payload) {{
                        results.push({{ from: ev.data.payload.origin || domain, topics: ev.data.payload.topics || [] }});
                        cleanup();
                    }}
                }};

                const cleanup = () => {{
                    window.removeEventListener('message', onMessage);
                    try {{ document.body.removeChild(frame); }} catch(e){{}}
                    pending -= 1;
                    if (pending === 0) finish();
                }};

                window.addEventListener('message', onMessage);

                // When the frame loads, send a request for topics
                frame.onload = () => {{
                    try {{ frame.contentWindow.postMessage({{ type: 'getTopics', skipObservation: !observe.checked }}, '*'); }} catch(e) {{ cleanup(); }}
                }};

                // Timeout in case of failure
                setTimeout(() => {{ if (document.body.contains(frame)) cleanup(); }}, 10000);
            }} catch (err) {{
                pending -= 1;
                if (pending === 0) finish();
            }}
        }});
    }});
    </script>
</body>
</html>
""".format(
        adhost=adhost, domains_json=domains_json, port=port
    )


def make_local_adtech_frame():
    # Similar to topics-demo/adtech-phase2.html but embedded per-site.
    return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Ad Tech Frame (local)</title>
    <meta http-equiv="Permissions-Policy" content="browsing-topics=*">
    <style>
        body { font-family: system-ui, sans-serif; background: #fafafa; padding: 12px; }
        pre { background: #fff; padding: 12px; border-radius: 8px; border: 1px solid #eee; max-height: 240px; overflow:auto;}
        .row { display:flex; gap:10px; align-items:center; margin-bottom:10px; flex-wrap: wrap;}
        .pill { padding:2px 8px; border-radius:999px; background:#efefef; font-size:12px; }
        button { padding:8px 10px; border-radius:10px; border:1px solid #ddd; background:#fff; cursor:pointer; }
        button:disabled { opacity:.6; cursor:not-allowed; }
    </style>
</head>
<body>
    <h2>Ad Tech Frame (local)</h2>
    <div class="row">
        <span id="support" class="pill">detecting…</span>
        <label><input id="observe" type="checkbox" checked> observe (skipObservation = false)</label>
        <button id="callSelf" disabled>Call Topics (iframe)</button>
        <button id="clearWitness">Clear Witness Log</button>
        <button id="clearLog">Clear Topics Log</button>
    </div>
    <pre id="output">—</pre>

    <script type="module">
        import { getWitnesses, clearWitnesses, logTopics, getTopicLog, clearTopicLog } from "./witness.js";

        const output = document.getElementById("output");
        const callSelf = document.getElementById("callSelf");
        const observe = document.getElementById("observe");
        const support = document.getElementById("support");
        const btnClearW = document.getElementById("clearWitness");
        const btnClearL = document.getElementById("clearLog");

        const supported = typeof document.browsingTopics === "function";
        support.textContent = supported ? "document.browsingTopics() available" : "Not supported in iframe";
        support.style.background = supported ? "#d9f7be" : "#ffd6e7";
        callSelf.disabled = !supported;

        function normalize(topics) {
            return (Array.isArray(topics) ? topics : []).map(t => ({
                topic: t.topic ?? null,
                name: t.name || t.topicName || String(t),
                taxonomyVersion: t.taxonomyVersion ?? null
            }));
        }

        function postWitness(origin, topics) {
            if (!Array.isArray(topics) || topics.length === 0) return;
            try {
                fetch('/__adtech_witness', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ origin, topics })
                }).catch(()=>{});
            } catch (e) {}
        }

        function render(from, topics) {
            const witnesses = getWitnesses();
            const normalized = normalize(topics);
            const annotated = normalized.map(t => ({
                ...t,
                witnessed: witnesses.has(t.name)
            }));
            logTopics(from, annotated);
            const history = getTopicLog();
            output.textContent = JSON.stringify({
                latest: { from, topics: annotated },
                witnessed: [...witnesses],
                historyCount: history.length
            }, null, 2);
            return normalized;
        }

        window.addEventListener("message", (event) => {
            if (!event?.data) return;
                if (event.data.type === "topicsData") {
                    const normalized = render("publisher -> adtech", event.data.payload);
                    postWitness(location.hostname, normalized);
                }
                if (event.data.type === "topicsResponse") {
                    try {
                        const payload = event.data.payload || {};
                        const topics = payload.topics || payload || [];
                        const normalized = render("publisher -> adtech", topics);
                        postWitness(payload.origin || location.hostname, normalized);
                    } catch (e) {}
                }
            if (event.data.type === "declareCategory") {
                try {
                    const cat = event.data.payload;
                    const set = new Set(JSON.parse(localStorage.getItem("adtech_witnessed_topics") || "[]"));
                    set.add(cat);
                    localStorage.setItem("adtech_witnessed_topics", JSON.stringify([...set]));
                } catch {};
            }
            if (event.data.type === "clearWitnesses") {
                clearWitnesses();
                output.textContent = "Witness log cleared.";
            }
        });

        async function getTopicsSelf() {
            output.textContent = "Iframe querying…";
            try {
                const topics = await document.browsingTopics({ skipObservation: !observe.checked });
                const normalized = render("adtech iframe", topics);
                postWitness(location.hostname, normalized);
            } catch (err) {
                output.textContent = "Iframe Error: " + err.message;
            }
        }
        callSelf.addEventListener("click", getTopicsSelf);

        btnClearW.addEventListener("click", () => {
            clearWitnesses();
            output.textContent = "Witness log cleared.";
        });
        btnClearL.addEventListener("click", () => {
            clearTopicLog();
            output.textContent = "Topics log cleared.";
        });

        if (supported) getTopicsSelf();
    </script>
</body>
</html>
"""


def find_mkcert():
    return shutil.which("mkcert")


def run_mkcert(domains, cert_file: Path, key_file: Path):
    mkcert = find_mkcert()
    if not mkcert:
        print("mkcert is not installed or not on PATH.")
        print("Install mkcert and run `mkcert -install` before using this script.")
        return False
    cmd = [mkcert, "-cert-file", str(cert_file), "-key-file", str(key_file)] + domains
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd, cwd=str(ROOT))
    return True


def make_hosts_lines(domains):
    lines = [f"127.0.0.1\t{d}" for d in domains]
    return lines


def update_etc_hosts(domains):
    hosts_path = Path("/etc/hosts")
    if not hosts_path.exists():
        print("/etc/hosts not found; cannot update hosts file.")
        return False
    lines = make_hosts_lines(domains)
    to_add = [l + "\n" for l in lines]
    print("Will append the following lines to /etc/hosts:")
    for l in lines:
        print("  ", l)
    try:
        with hosts_path.open("a", encoding="utf-8") as f:
            f.writelines(to_add)
    except PermissionError:
        print(
            "Permission denied: run this script as root or re-run with sudo to update /etc/hosts."
        )
        return False
    return True


TAG_START = "# BEGIN topics-api final-demo"
TAG_END = "# END topics-api final-demo"


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument(
        "--hosts",
        choices=["install", "remove", "show"],
        help="Manage /etc/hosts entries for generated sites",
    )
    p.add_argument(
        "--json",
        default=str(DEFAULT_JSON),
        help="Path to the topics->domains JSON file",
    )
    p.add_argument(
        "--cert-name", default="cert", help="Base name for output cert and key files"
    )
    p.add_argument(
        "--no-cert",
        action="store_true",
        help="Do not attempt to create a certificate (skip mkcert)",
    )
    p.add_argument(
        "--mkcert-install",
        action="store_true",
        help="Run `mkcert -install` before creating the certificate",
    )
    p.add_argument(
        "--adhost",
        default="adtech.test",
        help="Hostname to use for the global advertiser iframe",
    )
    return p.parse_args()


def main():
    args = parse_args()
    json_path = Path(args.json)
    if not json_path.exists():
        print(f"JSON file not found: {json_path}")
        sys.exit(1)
    mapping = load_mapping(json_path)
    domain_topics = invert_mapping(mapping)
    domains = sorted(domain_topics.keys())

    print(f"Creating site folders for {len(domains)} domains under: {SITES_DIR}")

    # Determine port used for generated iframe URLs
    port = int(os.environ.get("PORT", "8080"))

    adhost = args.adhost  # Restore adhost variable for downstream calls
    create_site_files(domain_topics, adhost, port)

    # Create a single shared adtech page and witness helper at the repo root.
    # This allows every generated site to embed `/adtech.html` (served via
    # the host-aware server fallback) without creating per-site ad pages.
    try:
        adtech_path = ROOT / "adtech.html"
        # Always (re)create the shared adtech frame so it stays in sync
        # with the template in this script. Overwrite existing file.
        adtech_path.write_text(make_local_adtech_frame(), encoding="utf-8")

        # Ensure a shared witness.js is available at the repo root so the
        # adtech page can import `./witness.js` when served under any site host.
        root_witness = ROOT / "witness.js"
        src_witness = ROOT.parent.joinpath("topics-demo", "witness.js")
        if src_witness.exists():
            shutil.copyfile(src_witness, root_witness)
        else:
            # Fallback minimal witness implementation (matches the previous per-site fallback)
            root_witness.write_text(
                """// Minimal witness helper
export function getWitnesses(){try{return new Set(JSON.parse(localStorage.getItem('adtech_witnessed_topics')||'[]'))}catch{return new Set()}}
export function recordWitness(t){const s=getWitnesses();s.add(t);localStorage.setItem('adtech_witnessed_topics',JSON.stringify([...s]))}
export function clearWitnesses(){localStorage.removeItem('adtech_witnessed_topics')}
export function logTopics(src,topics){try{const k='adtech_topics_log';const e=JSON.parse(localStorage.getItem(k)||'[]');e.push({ts:new Date().toISOString(),source:src,topics});localStorage.setItem(k,JSON.stringify(e))}catch(e){}}
export function getTopicLog(){try{return JSON.parse(localStorage.getItem('adtech_topics_log')||'[]')}catch{return []}}
export function clearTopicLog(){localStorage.removeItem('adtech_topics_log')}
""",
                encoding="utf-8",
            )
    except Exception:
        print("Warning: failed to create shared adtech or witness files in repo root")

    cert_file = ROOT / f"{args.cert_name}-cert.pem"
    key_file = ROOT / f"{args.cert_name}-key.pem"

    # Hosts utilities
    def make_hosts_block(domains):
        lines = [TAG_START] + [f"127.0.0.1\t{d}" for d in domains] + [TAG_END]
        return "\n".join(lines) + "\n"

    def install_hosts(domains):
        hosts_path = Path("/etc/hosts")
        existing = hosts_path.read_text(encoding="utf-8") if hosts_path.exists() else ""
        pattern = re.compile(
            re.escape(TAG_START) + r".*?" + re.escape(TAG_END) + r"\n?", re.S
        )
        new_content = (
            pattern.sub("", existing).rstrip() + "\n\n" + make_hosts_block(domains)
        )
        if os.geteuid() == 0:
            hosts_path.write_text(new_content, encoding="utf-8")
        else:
            tmp = ROOT / "hosts.tmp"
            tmp.write_text(new_content, encoding="utf-8")
            subprocess.check_call(["sudo", "cp", str(tmp), str(hosts_path)])
            tmp.unlink()

    def remove_hosts():
        hosts_path = Path("/etc/hosts")
        if not hosts_path.exists():
            print("/etc/hosts not found; nothing to remove.")
            return False
        existing = hosts_path.read_text(encoding="utf-8")
        pattern = re.compile(
            re.escape(TAG_START) + r".*?" + re.escape(TAG_END) + r"\n?", re.S
        )
        new_content = pattern.sub("", existing)
        if os.geteuid() == 0:
            hosts_path.write_text(new_content, encoding="utf-8")
        else:
            tmp = ROOT / "hosts.tmp"
            tmp.write_text(new_content, encoding="utf-8")
            subprocess.check_call(["sudo", "cp", str(tmp), str(hosts_path)])
            tmp.unlink()
        return True

    def show_hosts_block():
        hosts_path = Path("/etc/hosts")
        if not hosts_path.exists():
            print("/etc/hosts not found")
            return
        existing = hosts_path.read_text(encoding="utf-8")
        m = re.search(
            re.escape(TAG_START) + r".*?" + re.escape(TAG_END), existing, re.S
        )
        if m:
            print(m.group(0))
        else:
            print("No managed hosts block present in /etc/hosts")

    # Optional mkcert install
    if args.mkcert_install:
        mkcert = find_mkcert()
        if not mkcert:
            print("mkcert is not installed or not on PATH; cannot run mkcert -install.")
        else:
            try:
                print("Running: mkcert -install")
                subprocess.check_call([mkcert, "-install"], cwd=str(ROOT))
            except subprocess.CalledProcessError as e:
                print("mkcert -install failed:", e)

    # Certificate creation
    if args.no_cert:
        print("\nSkipping certificate creation because --no-cert was passed.")
        ok = False
    else:
        print("\nGenerating TLS certificate with mkcert (required by default)...")
        mkcert = find_mkcert()
        if not mkcert:
            print("Error: mkcert is not installed or not on PATH.")
            print(
                "Install mkcert and run `mkcert -install`, or re-run with --no-cert to skip certificate creation."
            )
            sys.exit(2)
        try:
            ok = run_mkcert(domains, cert_file, key_file)
        except subprocess.CalledProcessError as e:
            print("mkcert failed:", e)
            ok = False

    if ok:
        print(f"Created cert: {cert_file} and key: {key_file}")
    else:
        if args.no_cert:
            print("No certificate was created (user requested --no-cert).")
        else:
            print(
                "Certificate was not created. You can create one manually with mkcert:"
            )
            print(
                "  mkcert -cert-file cert.pem -key-file key.pem "
                + " ".join(domains[:10])
                + " ..."
            )

    # Hosts management actions (install/remove/show)
    if args.hosts:
        action = args.hosts
        if action == "install":
            print("\nInstalling hosts block into /etc/hosts (may prompt for sudo)...")
            try:
                install_hosts(domains)
                print("Hosts block installed. Remove with --hosts remove")
            except subprocess.CalledProcessError as e:
                print("Failed to update /etc/hosts:", e)
        elif action == "remove":
            print("\nRemoving hosts block from /etc/hosts (may prompt for sudo)...")
            try:
                removed = remove_hosts()
                if removed:
                    print("Hosts block removed.")
            except subprocess.CalledProcessError as e:
                print("Failed to remove hosts block:", e)
        elif action == "show":
            show_hosts_block()
        else:
            print("Unknown hosts action:", action)
    else:
        print(
            "\nTo access these sites locally, add the following lines to /etc/hosts (or run with --hosts install):"
        )
        for l in make_hosts_lines(domains):
            print("  ", l)

    print("\nNext: run `python3 https_server.py` inside the `final-demo` directory.")


if __name__ == "__main__":
    main()
